#!/usr/bin/python

bnchmrk="hull"
benchmark="Convex Hull"
checkProgram="../common/hullCheck"
dataDir = "../geometryData/data"

tests = [
    [10, "2DinSphere_100000000","", ""],
    [5, "2Dkuzmin_100000000","", ""],
    [1, "2DonSphere_100000000","", ""]
    ]

small_tests = [
    [10, "2DinSphere_10000000","", ""],
    [5, "2Dkuzmin_10000000","", ""],
    [1, "2DonSphere_10000000","", ""]
    ]

import runTests
if runTests.getOption("--small"):
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, small_tests)
else:
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

