include parallelDefs

# required files
GLOBAL_REQUIRE = utils.h parallel.h sequence.h deterministicHash.h
LOCAL_REQUIRE = 
INCLUDE = deterministicHash.h

include ../common/timeRequiredFiles
include MakeBenchI
