include parallelDefs

# required files
SORT = sampleSort.h quickSort.h transpose.h
GLOBAL_REQUIRE = parallel.h sequence.h $(SORT)
LOCAL_REQUIRE = 
INCLUDE = sampleSort.h

include ../common/timeRequiredFiles
include MakeBenchI
