#!/usr/bin/python

bnchmrk="refine"
benchmark="Delaunay Refinement"
checkProgram="../common/refineCheck"
dataDir = "../geometryData/data"

tests = [
    [1, "2DinCubeDelaunay_5000000","",""],
    [1, "2DkuzminDelaunay_5000000","",""],
    ]

small_tests = [
    [1, "2DinCubeDelaunay_50000","",""],
    [1, "2DkuzminDelaunay_50000","",""],
    ]

import runTests
if runTests.getOption("--small"):
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, small_tests)
else:
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

