#!/usr/bin/python

bnchmrk="matching"
benchmark="Maximal Matching"
checkProgram="../common/matchingCheck"
dataDir = "../graphData/data"

tests = [
    [1, "randLocalGraph_E_5_40000000", "", ""],
    [1, "rMatGraph_E_5_40000000", "", ""],
    [1, "2Dgrid_E_64400000", "", ""]
    ]

small_tests = [
    [1, "randLocalGraph_E_5_400000", "", ""],
    [1, "rMatGraph_E_5_400000", "", ""],
    [1, "2Dgrid_E_644000", "", ""]
    ]

import runTests
if runTests.getOption("--small"):
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, small_tests)
else:
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

