#!/usr/bin/python

bnchmrk="remDups"
benchmark="Remove Duplicates"
checkProgram="../common/remDupsCheck"
dataDir = "../sequenceData/data"

tests = [
    [1, "randomSeq_100M_int", "", ""],
    [1, "randomSeq_100M_100K_int", "", ""],
    [1, "exptSeq_100M_int", "", ""],
    [3, "trigramSeq_100M", "", ""],
    [3, "trigramSeq_100M_pair_int", "", ""]
    ]

small_tests = [
    [1, "randomSeq_10M_int", "", ""],
    [1, "randomSeq_10M_10K_int", "", ""],
    [1, "exptSeq_10M_int", "", ""],
    [3, "trigramSeq_10M", "", ""],
    [3, "trigramSeq_10M_pair_int", "", ""]
    ]

import runTests
if runTests.getOption("--small"):
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, small_tests)
else:
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)
