#!/usr/bin/python

bnchmrk="delaunay"
benchmark="Delaunay Triangulation"
checkProgram="../common/delaunayCheck"
dataDir = "../geometryData/data"

tests = [
    [1, "2DinCube_10M","",""],
    [1, "2Dkuzmin_10M","",""]
    ]

small_tests = [
    [1, "2DinCube_1M","",""],
    [1, "2Dkuzmin_1M","",""]
    ]

import runTests
if runTests.getOption("--small"):
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, small_tests)
else:
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)


