#!/usr/bin/python

bnchmrk="SA"
benchmark="Suffix Array"
checkProgram="../common/SACheck"
dataDir = "../sequenceData/data"

tests = [
    [1, "trigramString_100000000", "", ""],
    [3, "chr22.dna", "", ""],
    [1, "etext99", "", ""],
    [1, "wikisamp.xml", "", ""]
]

small_tests = [
    [1, "trigramString_1000000", "", ""],
]

import runTests
if runTests.getOption("--small"):
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, small_tests)
else:
    runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

