include parallelDefs

# required files
OCTTREE = geometry.h octTree.h blockRadixSort.h transpose.h
GLOBAL_REQUIRE = parallel.h sequence.h $(OCTTREE)
BENCH_REQUIRE = spherical.h
OBJS = CK.o

include ../common/timeRequiredFiles
include MakeBench
